### ISSUE TITLE
Benchmarks unable to download Tomcat: http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz

### ISSUE THREAD

**Issue by karlmdavis** [karlmdavis/rps-tourney#109]
I just checked manually, and that release has been removed; only the latest is available there. Oops.

```
org.codehaus.cargo.container.ContainerException: Failed to download [http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz]
	at org.codehaus.cargo.container.installer.ZipURLInstaller.download(ZipURLInstaller.java:446)
	at org.codehaus.cargo.container.installer.ZipURLInstaller.install(ZipURLInstaller.java:222)
	at com.justdavis.karl.tomcat.LocallyInstalledTomcatServer.install(LocallyInstalledTomcatServer.java:207)
	at com.justdavis.karl.tomcat.LocallyInstalledTomcatServer.<init>(LocallyInstalledTomcatServer.java:55)
	at com.justdavis.karl.tomcat.TomcatServerHelper.createLocallyInstalledServer(TomcatServerHelper.java:23)
	at org.rps.tourney.service.benchmarks.state.LocalServerManager.<init>(LocalServerManager.java:60)
	at org.rps.tourney.service.benchmarks.state.ServerState.setup(ServerState.java:40)
	at org.rps.tourney.benchmarks.webapp.generated.WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest._jmh_tryInit_f_serverstate3_G(WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest.java:492)
	at org.rps.tourney.benchmarks.webapp.generated.WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest.retrieveGameHtmlOnlyAsUnauthenticatedUser_Throughput(WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: in cargo code: Can't get http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz to /tmp/cargo/installs/apache-tomcat-7.0.65.tar.gz
	at org.apache.tools.ant.taskdefs.Get.doGet(Get.java:199)
	at org.apache.tools.ant.taskdefs.Get.execute(Get.java:78)
	at org.codehaus.cargo.container.installer.ZipURLInstaller.doDownload(ZipURLInstaller.java:487)
	at org.codehaus.cargo.container.installer.ZipURLInstaller.download(ZipURLInstaller.java:426)
	... 18 more
in cargo code: Can't get http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz to /tmp/cargo/installs/apache-tomcat-7.0.65.tar.gz
	at org.apache.tools.ant.taskdefs.Get.doGet(Get.java:199)
	at org.apache.tools.ant.taskdefs.Get.execute(Get.java:78)
	at org.codehaus.cargo.container.installer.ZipURLInstaller.doDownload(ZipURLInstaller.java:487)
	at org.codehaus.cargo.container.installer.ZipURLInstaller.download(ZipURLInstaller.java:426)
	at org.codehaus.cargo.container.installer.ZipURLInstaller.install(ZipURLInstaller.java:222)
	at com.justdavis.karl.tomcat.LocallyInstalledTomcatServer.install(LocallyInstalledTomcatServer.java:207)
	at com.justdavis.karl.tomcat.LocallyInstalledTomcatServer.<init>(LocallyInstalledTomcatServer.java:55)
	at com.justdavis.karl.tomcat.TomcatServerHelper.createLocallyInstalledServer(TomcatServerHelper.java:23)
	at org.rps.tourney.service.benchmarks.state.LocalServerManager.<init>(LocalServerManager.java:60)
	at org.rps.tourney.service.benchmarks.state.ServerState.setup(ServerState.java:40)
	at org.rps.tourney.benchmarks.webapp.generated.WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest._jmh_tryInit_f_serverstate3_G(WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest.java:492)
	at org.rps.tourney.benchmarks.webapp.generated.WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest.retrieveGameHtmlOnlyAsUnauthenticatedUser_Throughput(WebAppGameDisplayBenchmarks_retrieveGameHtmlOnlyAsUnauthenticatedUser_jmhTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by karlmdavis** [comment]
Resolved in https://github.com/karlmdavis/jessentials/commit/890afbe6894be1cb5ad4e0a2be5e206cf45d2dc6.
