### ISSUE TITLE
Intermittent test failures in GameSessionResourceImplIT

### ISSUE THREAD

**Issue by karlmdavis** [karlmdavis/rps-tourney#37]
Here's an example failsafe log from a week or three ago for such a failure:

```
-------------------------------------------------------------------------------
Test set: com.justdavis.karl.rpstourney.service.app.game.GameSessionResourceImplIT
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.073 sec <<< FAILURE! - in com.justdavis.karl.rpstourney.service.app.game.GameSessionResourceImplIT
submitThrowConcurrency(com.justdavis.karl.rpstourney.service.app.game.GameSessionResourceImplIT)  Time elapsed: 2.352 sec  <<< FAILURE!
java.lang.AssertionError: Both failed on attempt 30
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.justdavis.karl.rpstourney.service.app.game.GameSessionResourceImplIT.submitThrowConcurrency(GameSessionResourceImplIT.java:428)
```

Just a wild guess: this is likely due to a race condition.

**Comment by karlmdavis** [comment]
Here's another error I'm seeing in this test:

```
-------------------------------------------------------------------------------
Test set: com.justdavis.karl.rpstourney.service.app.game.GameResourceImplIT
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.531 sec <<< FAILURE! - in com.justdavis.karl.rpstourney.service.app.game.GameResourceImplIT
submitThrowConcurrency(com.justdavis.karl.rpstourney.service.app.game.GameResourceImplIT)  Time elapsed: 2.104 sec  <<< ERROR!
com.justdavis.karl.rpstourney.service.client.HttpClientException: Unexpected HTTP 500 status on response: Internal Server Error
	at com.justdavis.karl.rpstourney.service.client.game.GameClient.prepareRound(GameClient.java:226)
	at com.justdavis.karl.rpstourney.service.app.game.GameResourceImplIT.submitThrowConcurrency(GameResourceImplIT.java:511)
```

With the following in the Tomcat server log:

```
2015-05-05 22:34:22,371 [qtp500514267-40] WARN  o.e.jetty.servlet.ServletHandler - /games/yEVykclYpd/prepareRound
java.lang.RuntimeException: org.apache.cxf.interceptor.Fault: could not execute statement; SQL [n/a]; constraint ["PK_GAMEROUNDS"]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
... [edited to shorten massive stack trace]
Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["PK_GAMEROUNDS"]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:248) ~[spring-orm-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:214) ~[spring-orm-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757) ~[spring-tx-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726) ~[spring-tx-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:497) ~[spring-tx-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277) ~[spring-tx-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at com.justdavis.karl.rpstourney.service.app.game.GameResourceImpl$$EnhancerBySpringCGLIB$$a68afb3f.prepareRound(<generated>) ~[spring-core-4.1.2.RELEASE.jar:na]
	at com.justdavis.karl.rpstourney.service.app.game.GameResourceImpl$$FastClassBySpringCGLIB$$9f50d117.invoke(<generated>) ~[spring-core-4.1.2.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at com.justdavis.karl.rpstourney.service.app.game.GameResourceImpl$$EnhancerBySpringCGLIB$$fffe078a.prepareRound(<generated>) ~[spring-core-4.1.2.RELEASE.jar:na]
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source) ~[na:na]
... [edited to shorten massive stack trace]
```

**Comment by karlmdavis** [comment]
This took 10.7h to solve.
